- hosts: bot
  become: yes
  become_method: sudo
  roles:
    - db

- hosts: repl
  become: yes
  become_method: sudo
  roles:
    - db_repl

- hosts: bot
  become: yes
  become_method: sudo
  roles:
    - bot
